packaging_format = 2

id = "ifconfig-io"
name = "ifconfig-io"
description.en = "IP API service to get their public IP address."

version = "2024.04.20~ynh1"

maintainers = ["Fabian Wilkens"]

[upstream]
license = "MIT"
website = "https://ifconfig.io/"
demo = "https://ifconfig.io"
admindoc = "https://github.com/georgyo/ifconfig.io/"
userdoc = "https://github.com/georgyo/ifconfig.io/"
code = "https://github.com/georgyo/ifconfig.io/"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ifconfig"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/georgyo/ifconfig.io/archive/6c13119b0b9cbf21143e4ca912dae26521dce8ae.tar.gz"
        sha256 = "c61e36a3123c5fe48c0bd8c17b2a25f6af6f650ef4b5887df32096f4c5ce547e"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
