#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ifconfig-io"
name = "ifconfig-io"
description.en = "Tool to find your own IP address"
description.fr = "Outil pour trouver votre propre adresse IP"

version = "2024.12.29~ynh1"

maintainers = ["Fabian Wilkens"]

[upstream]
license = "MIT"
website = "https://ifconfig.io/"
demo = "https://ifconfig.io"
admindoc = "https://github.com/georgyo/ifconfig.io/"
userdoc = "https://github.com/georgyo/ifconfig.io/"
code = "https://github.com/georgyo/ifconfig.io/"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ifconfig"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/georgyo/ifconfig.io/archive/19d870ce4ad8f14458133fe5a30f862dbac50dce.tar.gz"
    sha256 = "56949a0f6f21ed615c548f60d80d25f0cc7004f19f2317755d2f2fc54563b9a1"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
