packaging_format = 2

id = "ifconfig-io"
name = "ifconfig-io"
description.en = "IP API service to get their public IP address."

version = "2024.01.06~ynh1"

maintainers = ["Fabian Wilkens"]

[upstream]
license = "MIT"
website = "https://ifconfig.io/"
demo = "https://ifconfig.io"
admindoc = "https://github.com/georgyo/ifconfig.io/"
userdoc = "https://github.com/georgyo/ifconfig.io/"
code = "https://github.com/georgyo/ifconfig.io/"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ifconfig"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/georgyo/ifconfig.io/archive/3233adac9a7ce721c1a0237788eb84237b0632b4.tar.gz"
        sha256 = "4722bb0d360cc897b6b51c7f51e2651231deedcdb5c7982ca4fc2d5b0b6c26a7"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
