packaging_format = 2

id = "ifconfig-io"
name = "ifconfig-io"
description.en = "IP API service to get their public IP address."

version = "2024.03.09~ynh1"

maintainers = ["Fabian Wilkens"]

[upstream]
license = "MIT"
website = "https://ifconfig.io/"
demo = "https://ifconfig.io"
admindoc = "https://github.com/georgyo/ifconfig.io/"
userdoc = "https://github.com/georgyo/ifconfig.io/"
code = "https://github.com/georgyo/ifconfig.io/"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ifconfig"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/georgyo/ifconfig.io/archive/e62a94ac0ea60b87a7a7d71f1be7af3290c9c32a.tar.gz"
        sha256 = "4a0354a72e8199e6da4858edd35d11561f2fecd13e436108e2d0c008dbce6b49"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
